// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 09/07/2026, 18:52:22
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/ema/Scrivania/altri repooo/nuxt-cockpit-agent-starter/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/nuxt-cockpit-agent-starter/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/nuxt-cockpit-agent-starter/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/nuxt-cockpit-agent-starter/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/nuxt-cockpit-agent-starter/plugins/**/*.{js,ts,mjs}","/home/ema/Scrivania/altri repooo/nuxt-cockpit-agent-starter/composables/**/*.{js,ts,mjs}","/home/ema/Scrivania/altri repooo/nuxt-cockpit-agent-starter/utils/**/*.{js,ts,mjs}","/home/ema/Scrivania/altri repooo/nuxt-cockpit-agent-starter/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/nuxt-cockpit-agent-starter/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/nuxt-cockpit-agent-starter/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;